#### Exclude
exclude: [".rvmrc", ".rbenv-version", "README.md", "README_en.md", "Rakefile", "changelog.md"]

## there is some bug in github-page https://github.com/github/pages-gem/issues/613
## have to set theme to null. or there will be a file in _site/assets/css/style.css with wrong content
theme: null

#### Code Highlighter
# 'pygments' is unsupported on GitHub Pages now.
highlighter: rouge

#### Permalink
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: pretty

#### Markdown Processors
# 'redcarpet' is unsupported on GitHub Pages now.
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    block:
      line_numbers: true

#### Collections
collections:
  guides:
    output: true
  books:
    output: true

#### Default Attributes
defaults:
  - scope:
      path: "_guides"
    values:
      layout: "post"
      categories: "guide"
  - scope:
      path: "_books"
      type: "books"
    values:
      layout: "book"
  - scope:
      path: "_posts/algorithm"
    values:
      categories: "algorithm"
  - scope:
      path: "_posts/consul"
    values:
      categories: "consul"
  - scope:
      path: "_posts/docker"
    values:
      categories: "docker"
  - scope:
      path: "_posts/k8s"
    values:
      categories: "k8s"
  - scope:
      path: "_posts/istio"
    values:
      categories: "istio"
  - scope:
      path: "_posts/linux"
    values:
      categories: "linux"
  - scope:
      path: "_posts/life"
    values:
      categories: "life"
  - scope:
      path: "_posts/go"
    values:
      categories: "go"
  - scope:
      path: "_posts/git"
    values:
      categories: "git"
  - scope:
      path: "_posts/github"
    values:
      categories: "github"
  - scope:
      path: "_posts/nginx"
    values:
      categories: "nginx"
  - scope:
      path: "_posts/redis"
    values:
      categories: "redis"
  - scope:
      path: "_posts/zookeeper"
    values:
      categories: "zookeeper"
  - scope:
      path: "_posts/theory"
    values:
      categories: "theory"
  - scope:
      path: "_posts/others"
    values:
      categories: "others"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

#### Pagination
paginate: 20

#### Site
title : aimuke
tagline: Welcome to the real world!It sucks,but you're gonna love it
assets: /assets
url:
baseurl:

#### Language
language: zh-CN    ## blog site languages: en, zh-CN, zh-TW, de

#### Menu
menu:
  Home: /
  Guide: /guide
  Archives: /archives
  Tags: /tags
  Categories: /categories
  Books: /books
　About: /about

#### Widgets
widgets:
- category
- tagcloud
- links
- douban
- github-card
- rss
## provide seven widgets:github-card,category,tag,rss,archive,tagcloud,links,weibo,douban


#### RSS
rss: /atom.xml ## RSS address.

#### Image
imglogo:
  enable: true             ## display image logo true/false.
  src: img/avatar.jpg        ## `.svg` and `.png` are recommended,please put image into the theme folder `/jacman/source/img`.
favicon: img/favicon.ico   ## size:32px*32px,`.ico` is recommended,please put image into the theme folder `/jacman/source/img`.
apple_icon: img/jacman.jpg ## size:114px*114px,please put image into the theme folder `/jacman/source/img`.
author_img: img/avatar.jpg  ## size:220px*220px.display author avatar picture.if don't want to display,please don't set this.
banner_img: #img/banner.jpg ## size:1920px*200px+. Banner Picture

#### index post is expanding or not
index:
  expand: true           ## default is unexpanding,so you can only see the short description of each post.
  excerpt_link:  ##　Read More

close_aside: true  #close sidebar in post page if true
mathjax: true      #enable mathjax if true
share_to: true #enable share-to buttons if true

#### Author information
author:
  name: Lyu Bo      ## e.g. wuchong Author name
  intro_line1:  "welcome to my blog"    ## your introduction on the bottom of the page
  intro_line2:  "I will share some of lifes here."  ## the 2nd line
  weibo:      ## e.g. wuchong1014 or 2176287895 for http://weibo.com/2176287895
  weibo_verifier:  ## e.g. b3593ceb Your weibo-show widget verifier ,if you use weibo-show it is needed.
  tsina:      ## e.g. 2176287895  Your weibo ID,It will be used in share button.
  douban:     ## e.g. wuchong1014 or your id for https://www.douban.com/people/wuchong1014
  zhihu:      ## e.g. jark  for http://www.zhihu.com/people/jark
  email: lyu.bob101@gmail.com      ## e.g. imjark@gmail.com
  twitter:    ## e.g. jarkwu for https://twitter.com/jarkwu
  github: aimuke    ## e.g. wuchong for https://github.com/wuchong
  facebook:   ## e.g. imjark for https://facebook.com/imjark
  linkedin:   ## e.g. wuchong1014 for https://www.linkedin.com/in/wuchong1014
  google_plus:    ## e.g. "111190881341800841449" for https://plus.google.com/u/0/111190881341800841449, the "" is needed!
  stackoverflow:  ## e.g. 3222790 for http://stackoverflow.com/users/3222790/jark
## if you set them, the corresponding  share button will show on the footer

#### Toc
toc:
  article: false   ## show contents in article.
  aside: true     ## show contents in aside.
## you can set both of the value to true of neither of them.
## if you don't want display contents in a specified post,you can modify `front-matter` and add `toc: false`.

#### Links
links:
  Github: https://github.com/aimuke
  Aimuke's Blog: https://github.com/aimuke/aimuke.github.io
  Jark's Blog: http://wuchong.me

#### Comment
duoshuo_shortname:    ## e.g. wuchong      your duoshuo short name.       website: http://duoshuo.com
disqus_shortname:      ## e.g. wuchong      your disqus short name.        website: http://disqus.com
hypercomments_id:     ## e.g. 91510        your hypercomments widget id.  website: http://hypercomments.com
yungentie_productkey: ## your netease yungentie product key.              website: https://gentie.163.com
gitalk:
  enable: true
  clientID: 1724730665a52a08ffbb
  clientSecret: 0e805a0f9791a5ad967b6a49c54aac39cff71e6d
  repo: aimuke.github.io
  owner: aimuke
  admin: [aimuke]
## set only one of them
## duoshuo will be shutting down on June 1, 2017

#### Share button
jiathis:
  enable: false ## if you use jiathis as your share tool,the built-in share tool won't be display.
  id:    ## e.g. 1889330 your jiathis ID.
  tsina: ## e.g. 2176287895 Your weibo id,It will be used in share button.

#### Analytics
google_analytics:
  enable: false
  id:        ## e.g. UA-46321946-2 your google analytics ID.
  site:      ## e.g. wuchong.me your google analytics site or set the value as auto.
## You MUST upgrade to Universal Analytics first!
## https://developers.google.com/analytics/devguides/collection/upgrade/?hl=zh_CN
baidu_tongji:
  enable: false
  sitecode:  ## e.g. e6d1f421bbc9962127a50488f9ed37d1 your baidu tongji site code
cnzz_tongji:
  enable: false
  siteid:    ## e.g. 1253575964 your cnzz tongji site id

#### Miscellaneous
fancybox: true        ## if you use gallery post or want use fancybox please set the value to true.
totop: true           ## if you want to scroll to top in every post set the value to true

#### Custom Search
google_cse:
  enable: false
  cx: 018294693190868310296:abnhpuysycw  ## e.g. 018294693190868310296:abnhpuysycw your Custom Search ID.
## https://www.google.com/cse/
## To enable the custom search You must create a "search" folder in '/source' and a "index.md" file
## set the 'front-matter' as
## layout: search
## title: search
## ---
baidu_search:     ## http://zn.baidu.com/
  enable: false
  id:   ## e.g. "783281470518440642"  for your baidu search id
  site: http://zhannei.baidu.com/cse/search  ## your can change to your site instead of the default site
tinysou_search:     ## http://tinysou.com/
  enable: false
  id:  ## e.g. "4ac092ad8d749fdc6293" for your tiny search id
simple_jekyll_search:
  enable: true
  fulltext: false

plugins:
 - jemoji
